### ISSUE TITLE
Is there or will there be support for C/C++?

### ISSUE THREAD

**Issue by for-just-we** [IBM/tree-sitter-codeviews#25]
I would like to use a lightweight tool to analyze C/C++ code, but I notice comex only support Java/C# now.

**Comment by NobleMathews** [comment]
Hi @for-just-we! Thank you for trying out comex! We currently do not have immediate plans to implement support for C/C++. Our current implementation prioritizes Java and C# due to their alignment with our ML4SE Research objectives and requirements.

If you'd like to use comex as a foundation, you can refer to the existing Java and C# implementations and extend them. Since tree-sitter parsers are readily available for C/C++ too, you have the opportunity to contribute to comex by doing so. Your contributions are highly welcome! 🌟

We'll keep your request in mind for future enhancements. If you have any more feedback or questions, feel free to share. Thanks again!
